### ISSUE TITLE
Category button broken due to change in item card partial.

### ISSUE THREAD

**Issue by SergioMEV** [uiowahjmjohnsonselt2023/matts-marketplace#32]
**Describe the bug**
The category button broke because of a change in the item partial. I think we need to change the search function that the category buttons use so that it includes the keyword path thing that Haruko added.

On further inspection, all of the search buttons break because they don't have the path_keyword variable. We need to add it to all the functions in the items controller.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mattsperanza** [comment]
I don't think we need to change all the files we can just change the itemcard partial to handle that variable not existing with the defined?(path_keyword) function.

**Comment by dtlaurianti** [comment]
No longer relevant, search updated
