### ISSUE TITLE
Navbar Links not user friendly

### ISSUE THREAD

**Issue by dtlaurianti** [uiowahjmjohnsonselt2023/matts-marketplace#36]
**Describe the bug**
Not all of the highlighted area on the navbar icons is clickable to travel to the link.

**To Reproduce**
1. Run the server
2. Click the profile/chat icons in the white space
3. Not redirected

**Expected behavior**
If the mouse hover is highlighting the area then clicking should cause action.

**Comment by SergioMEV** [comment]
Done!
