### ISSUE TITLE
Can edit and destroy other users

### ISSUE THREAD

**Issue by harooks** [uiowahjmjohnsonselt2023/matts-marketplace#43]
**Describe the bug**
Users can access other member and edit/destroy them.

**To Reproduce**
1. Go to `/buyers`
2. Click on any item's detail button
3. Clock on user's name
4. end up at `users/:id`, where you will see edit and destroy button. 

**Expected behavior**
Users should be able to access profiles, but not edit or destroy them.

**Comment by mingilee98** [comment]
I will address this issue in my next pr!
