### ISSUE TITLE
No first name last name field in Profile Causing review 

### ISSUE THREAD

**Issue by harooks** [uiowahjmjohnsonselt2023/matts-marketplace#50]
**Describe the bug**
There's no place to enter first name and last name when signing up. 
When signing in we should be redirected to the profile page where users have to enter their first and last name.
@mingilee98 Did you do this? Without this we can't put reviews. 

**To Reproduce**
Given you created a new user (without first and last name)
1. Click on someone's profile
2. Try to add review
3. See error

**Expected behavior**
We should be able to review using our first and last names

**Comment by mingilee98** [comment]
Resolved
