### ISSUE TITLE
featured item checkbox doesn't display amount feature paid until refresh

### ISSUE THREAD

**Issue by SergioMEV** [uiowahjmjohnsonselt2023/matts-marketplace#60]
**Describe the bug**
The checkbox in the new item view for featuring the item doesn't display the featured amount paid textbox until after you reload the page. I had to change some of the js and this broke. I'll fix it.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dtlaurianti** [comment]
Fixed by my changes
